apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ebs-kube-rbac-proxy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-kube-rbac-proxy-role
subjects:
- kind: ServiceAccount
  name: aws-ebs-csi-driver-controller-sa
  namespace: ${NAMESPACE}
