kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-file-csi-driver-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
