# Grant controller access to leases
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manila-csi-driver-lease-leader-election
  namespace: openshift-manila-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manila-csi-driver-lease-leader-election
subjects:
- kind: ServiceAccount
  name: manila-csi-driver-controller-sa
  namespace: openshift-manila-csi-driver
