apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-aws-efs-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: aws-efs-cloud-credentials
    namespace: ${NAMESPACE}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      # https://github.com/openshift/aws-efs-csi-driver/blob/master/docs/iam-policy-example.json
      - elasticfilesystem:DescribeAccessPoints
      - elasticfilesystem:DescribeFileSystems
      - elasticfilesystem:DescribeMountTargets
      - elasticfilesystem:CreateAccessPoint
      - elasticfilesystem:DeleteAccessPoint
      - elasticfilesystem:TagResource
      - ec2:DescribeAvailabilityZones # for one-zone volumes
      resource: "*"
  # STS fields will be set by the operator
