kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    config.openshift.io/inject-proxy: csi-driver
    config.openshift.io/inject-proxy-cabundle: csi-driver
spec:
  template:
    spec:
      # We need hostNetwork in order to access the metadata service as it's a link-local address.
      # This also implies the use of the 'privileged' SCC.
      hostNetwork: true
      containers:
        - name: csi-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: ${DRIVER_IMAGE}
          imagePullPolicy: IfNotPresent
          args :
            - /bin/cinder-csi-plugin
            - "--provide-controller-service=false"
            - "--provide-node-service=true"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-config=$(CLOUD_CONFIG)"
            - "--with-topology=$(ENABLE_TOPOLOGY)"
            - "--v=${LOG_LEVEL}"
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/kubernetes/config/cloud.conf
            - name: ENABLE_TOPOLOGY
              valueFrom:
                configMapKeyRef:
                  key: enable_topology
                  name: cloud-conf
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: socket-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
              mountPropagation: "HostToContainer"
            - name: etc-selinux
              mountPath: /etc/selinux
            - name: sys-fs
              mountPath: /sys/fs
            # credentials and configuration
            - name: cacert
              mountPath: /etc/kubernetes/static-pod-resources/configmaps/cloud-config
              readOnly: true
            - name: config-cinderplugin
              mountPath: /etc/kubernetes/config
              readOnly: true
            - name: cloud-credentials
              mountPath: /etc/kubernetes/secret
              readOnly: true
          ports:
            - name: healthz
              containerPort: 10300
              protocol: TCP
          livenessProbe:
            httpGet:
              host: 127.0.0.1
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: cloud-credentials
          secret:
            secretName: openstack-cloud-credentials
            items:
              - key: clouds.yaml
                path: clouds.yaml
        - name: config-cinderplugin
          configMap:
            name: cloud-conf
            items:
              - key: cloud.conf
                path: cloud.conf
        - name: cacert
          configMap:
            name: cloud-conf
            items:
              - key: ca-bundle.pem
                path: ca-bundle.pem
            optional: true
