kind: Deployment
apiVersion: apps/v1
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          # The Topology feature gate can only be enabled or disabled via a command-line option,
          # so we need to do this dance of copying the value from the config map to the environment
          # so that we can use the environment variable in our CLI option.
          env:
            - name: ENABLE_TOPOLOGY
              valueFrom:
                configMapKeyRef:
                  key: enable_topology
                  name: cloud-conf
