language: en-US
reviews:
  profile: chill
  high_level_summary: false
  review_status: true
  commit_status: true
  collapse_walkthrough: true
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  poem: false
  suggested_labels: false
  path_filters:
  - "!vendor/**"
  tools:
    golangci-lint:
      enabled: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
    - AGENTS.md
  learnings:
    scope: local
