FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17 AS builder
WORKDIR /go/src/github.com/openshift/csi-operator
COPY . .
RUN make

FROM registry.ci.openshift.org/ocp/4.17:base-rhel9
COPY --from=builder /go/src/github.com/openshift/csi-operator/bin/create-efs-volume /usr/bin/
ENTRYPOINT ["/usr/bin/create-efs-volume"]
LABEL io.k8s.display-name="OpenShift AWS EFS Creator" \
	io.k8s.description="The AWS EFS CSI Creator creates a EFS filesystem for testing."
