apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: file.csi.azure.com
  annotations:
    # Used to determine if a CSI driver was created by OCP or by 3rd party operator / helm / yaml files.
    csi.openshift.io/managed: "true"
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: "privileged"
spec:
  fsGroupPolicy: "None"
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
