apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: samba-allow-all-egress
spec:
  podSelector:
    matchLabels:
      openshift.storage.samba.network-policy.all-egress: allow
  egress:
  - {}
  policyTypes:
  - Egress
