kind: Deployment
apiVersion: apps/v1
spec:
  template:
    metadata:
      annotations:
        openshift.io/required-scc: privileged
      labels:
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.metrics-range: allow
        openshift.storage.network-policy.all-egress: allow
    spec:
      containers:
        - name: csi-driver
          image: ${DRIVER_IMAGE}
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --metrics-address=localhost:${DRIVER_METRICS_PORT}
            - --v=${LOG_LEVEL}
          ports:
            - containerPort: 10307
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          securityContext:
            readOnlyRootFilesystem: true
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: socket-dir
          emptyDir: {}
