// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverDeployment) DeepCopyInto(out *CSIDriverDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverDeployment.
func (in *CSIDriverDeployment) DeepCopy() *CSIDriverDeployment {
	if in == nil {
		return nil
	}
	out := new(CSIDriverDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIDriverDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverDeploymentList) DeepCopyInto(out *CSIDriverDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CSIDriverDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverDeploymentList.
func (in *CSIDriverDeploymentList) DeepCopy() *CSIDriverDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CSIDriverDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CSIDriverDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverDeploymentSpec) DeepCopyInto(out *CSIDriverDeploymentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverDeploymentSpec.
func (in *CSIDriverDeploymentSpec) DeepCopy() *CSIDriverDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CSIDriverDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIDriverDeploymentStatus) DeepCopyInto(out *CSIDriverDeploymentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIDriverDeploymentStatus.
func (in *CSIDriverDeploymentStatus) DeepCopy() *CSIDriverDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CSIDriverDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
