spec:
  template:
    spec:
      volumes:
        # TODO(stephenfin): Remove in 4.22
        - name: legacy-cacert
          configMap:
            name: openstack-cloud-config
            items:
            - key: ca-bundle.pem
              path: ca-bundle.pem
            optional: true
