spec:
  template:
    spec:
      volumes:
        - name: legacy-cacert
          configMap:
            items:
            - key: ca-bundle.pem
              path: ca-bundle.pem
            name: openstack-cloud-config
            optional: true
