package operator

import (
	"context"
	"fmt"
	"time"

	"k8s.io/klog/v2"

	operatorapi "github.com/openshift/api/operator/v1"
	"github.com/openshift/csi-operator/pkg/clients"
	"github.com/openshift/library-go/pkg/controller/factory"
	"github.com/openshift/library-go/pkg/operator/events"
	"github.com/openshift/library-go/pkg/operator/status"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	defaultReSyncPeriod = 10 * time.Minute
)

type VersionController struct {
	name                     string
	controllerDeploymentName string
	commonClient             *clients.Clients
	eventRecorder            events.Recorder
}

func NewVersionController(
	name string,
	controllerDeploymentName string,
	commonClient *clients.Clients,
	eventRecorder events.Recorder) factory.Controller {

	c := &VersionController{
		name:                     name,
		controllerDeploymentName: controllerDeploymentName,
		commonClient:             commonClient,
		eventRecorder:            eventRecorder,
	}
	return factory.New().WithSync(
		c.Sync,
	).WithInformers(
		c.commonClient.ControlPlaneKubeInformers.InformersFor(c.commonClient.ControlPlaneNamespace).Apps().V1().Deployments().Informer(),
	).ResyncEvery(
		defaultReSyncPeriod,
	).ToController(
		name,
		eventRecorder,
	)
}

func hasFinishedProgressing(deployment *appsv1.Deployment) bool {
	if deployment.Status.ObservedGeneration != deployment.Generation {
		// The Deployment controller did not act on the Deployment spec change yet.
		// Any condition in the status may be stale.
		return false
	}
	// Deployment whose rollout is complete gets Progressing condition with Reason NewReplicaSetAvailable condition.
	// https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#complete-deployment
	for _, cond := range deployment.Status.Conditions {
		if cond.Type == appsv1.DeploymentProgressing {
			return cond.Status == corev1.ConditionTrue && cond.Reason == "NewReplicaSetAvailable"
		}
	}
	return false
}

func (c *VersionController) Sync(ctx context.Context, syncCtx factory.SyncContext) error {
	klog.Infof("VersionController sync started")
	defer klog.Infof("VersionController sync finished")

	opSpec, _, _, err := c.commonClient.OperatorClient.GetOperatorState()
	if err != nil {
		return err
	}
	if opSpec.ManagementState != operatorapi.Managed {
		return nil
	}

	deployment, err := c.commonClient.ControlPlaneKubeInformers.InformersFor(c.commonClient.ControlPlaneNamespace).Apps().V1().Deployments().Lister().Deployments(c.commonClient.ControlPlaneNamespace).Get(c.controllerDeploymentName)
	if err != nil {
		return fmt.Errorf("could not get Deployment %s in Namespace %s: %w", c.controllerDeploymentName, c.commonClient.ControlPlaneNamespace, err)
	}

	var desiredVersion string
	var actualVersion string
	for k, v := range deployment.Annotations {
		if k == "release.openshift.io/desired-version" {
			klog.Infof("VersionController: desiredVersion found: %s", v)
			desiredVersion = v
		} else if k == "release.openshift.io/version" {
			klog.Infof("VersionController: actualVersion found: %s", v)
			actualVersion = v
		}
	}

	// This operator adds "release.openshift.io/desired-version" annotation with its version for sure;
	// if the version from Annotations is not the same as operator version, we look at some outdated
	// deployment generated by another (previous) operator instance.
	if desiredVersion != status.VersionForOperatorFromEnv() {
		klog.Infof("VersionController: desiredVersion mismatch: \"%s\" vs \"%s\"", desiredVersion, status.VersionForOperatorFromEnv())
		return nil
	}

	// If versions from "release.openshift.io/version" and "release.openshift.io/desired-version"
	// annotations are equal, we have already populated these annotations before, do nothing now.
	if actualVersion == desiredVersion {
		klog.Infof("VersionController: version \"%s\" is already populated, nothing to do", desiredVersion)
		return nil
	}

	if hasFinishedProgressing(deployment) {
		klog.Infof("VersionController: deployment update is completed")
		updatedDeployment := setVersionAnnotation(deployment, desiredVersion)
		err := c.updateDeployment(ctx, updatedDeployment)
		if err != nil {
			return err
		}
		klog.Infof("VersionController: deployment updated with version %s", desiredVersion)
	} else {
		klog.Infof("VersionController: deployment update is in progress ...")
	}
	return nil
}

func (c *VersionController) updateDeployment(ctx context.Context, deployment *appsv1.Deployment) error {
	_, err := c.commonClient.ControlPlaneKubeClient.AppsV1().Deployments(c.commonClient.ControlPlaneNamespace).Update(ctx, deployment, metav1.UpdateOptions{})
	if err != nil {
		klog.Errorf("error updating deployment object %s in namespace %s: %v", deployment.Name, c.commonClient.ControlPlaneNamespace, err)
		return err
	}
	return nil
}

func setVersionAnnotation(deployment *appsv1.Deployment, version string) *appsv1.Deployment {
	// Create a deep copy of the PersistentVolume to avoid modifying the cached object
	deploymentCopy := deployment.DeepCopy()

	// Ensure the deployment has an annotations map
	if deploymentCopy.Annotations == nil {
		deploymentCopy.Annotations = make(map[string]string)
	}

	// Set or update the tag hash annotation
	deploymentCopy.Annotations["release.openshift.io/version"] = version

	return deploymentCopy
}
