apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-aws-efs-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: aws-efs-cloud-credentials
    namespace: ${NAMESPACE}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - elasticfilesystem:*
      resource: "*"
  # STS fields will be set by the operator
