apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-efs-csi-driver-controller-monitor
  namespace: ${NAMESPACE}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: provisioner-m
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: aws-efs-csi-driver-controller-metrics.${NAMESPACE}.svc
  jobLabel: component
  selector:
    matchLabels:
      app: aws-efs-csi-driver-controller-metrics
