apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aws-efs-allow-ingress-to-operator-metrics
spec:
  podSelector:
    matchLabels:
      openshift.storage.aws-efs.network-policy.operator-metrics: allow
  ingress:
  - ports:
    - protocol: TCP
      port: 8443
    from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-monitoring
  policyTypes:
  - Ingress
