kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smb-csi-driver-binding
subjects:
  - kind: ServiceAccount
    name: smb-csi-driver-node-sa
    namespace: ${NODE_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: smb-csi-driver-role
  apiGroup: rbac.authorization.k8s.io
