# SMB CSI inline volume needs the get permission for secrets
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smb-csi-driver-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
