apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
  annotations:
      # This CSIDriver is managed by an OCP CSI operator
      csi.openshift.io/managed: "true"
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  seLinuxMount: true
  volumeLifecycleModes:
    - Persistent
  nodeAllocatableUpdatePeriodSeconds: ${NODE_ALLOCATABLE_UPDATE_PERIOD_SECONDS}
